# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86183\Desktop\python-lxx\project2\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from Ui_untitled1 import Ui_Project2_20203578  #导入写的界面类
import time #时间计算
from rich.progress import track #rich库实现进度条
import numpy as np #构造一个小数的range 引入库实现读文件
from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd

#读文件 并且存到一个表格里 
city='sh'
data_sh = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\sh.xlsx")
#print(data)
Data_Array_sh = np.array(data_sh).flatten()
sh = Data_Array_sh.tolist()
#print(Data_List)

#北京'bj'
data_bj = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\bj.xlsx")
#print(data)
Data_Array_bj = np.array(data_bj).flatten()
bj = Data_Array_bj.tolist()
#print(bj)

#重庆 cq
data_cq = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\cq.xlsx")
#print(data)
Data_Array_cq = np.array(data_cq).flatten()
cq = Data_Array_cq.tolist()

#天津 tj
data_tj = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\tj.xlsx")
#print(data)
Data_Array_tj = np.array(data_tj).flatten()
tj = Data_Array_tj.tolist()

#哈尔滨 heb
data_heb = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\heb.xlsx")
#print(data)
Data_Array_heb = np.array(data_heb).flatten()
heb = Data_Array_heb.tolist()

#长春 cc
data_cc = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\cc.xlsx")
#print(data)
Data_Array_cc = np.array(data_cc).flatten()
cc = Data_Array_cc.tolist()

#沈阳 sy
data_sy = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\sy.xlsx")
#print(data)
Data_Array_sy = np.array(data_sy).flatten()
sy = Data_Array_sy.tolist()

#呼和浩特 hhht
data_hhht = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\hhht.xlsx")
#print(data)
Data_Array_hhht = np.array(data_hhht).flatten()
hhht = Data_Array_hhht.tolist()

#石家庄 sjz
data_sjz = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\sjz.xlsx")
#print(data)
Data_Array_sjz = np.array(data_sjz).flatten()
sjz = Data_Array_sjz.tolist()

#乌鲁木齐 wlmq
data_wlmq = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\wlmq.xlsx")
#print(data)
Data_Array_wlmq = np.array(data_wlmq).flatten()
wlmq = Data_Array_wlmq.tolist()

#兰州 lz
data_lz = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\lz.xlsx")
#print(data)
Data_Array_lz = np.array(data_lz).flatten()
lz = Data_Array_lz.tolist()


#西宁 xn 链家二手房没有这个城市
#data_xn = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\xn.xlsx")
#Data_Array_xn = np.array(data_xn).flatten()
#xn = Data_Array_xn.tolist()

#西安 xa
data_xa = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\xa.xlsx")
#print(data)
Data_Array_xa = np.array(data_xa).flatten()
xa = Data_Array_xa.tolist()

#银川 yc 盐城
data_yc = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\yc.xlsx")
#print(data)
Data_Array_yc = np.array(data_yc).flatten()
yc = Data_Array_yc.tolist()

#郑州 zz
data_zz = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\zz.xlsx")
#print(data)
Data_Array_zz = np.array(data_zz).flatten()
zz = Data_Array_zz.tolist()

#济南 jn
data_jn = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\jn.xlsx")
#print(data)
Data_Array_jn = np.array(data_jn).flatten()
jn = Data_Array_jn.tolist()

#太原 ty
data_ty = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\ty.xlsx")
#print(data)
Data_Array_ty = np.array(data_ty).flatten()
ty = Data_Array_ty.tolist()

#合肥 hf
data_hf = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\hf.xlsx")
#print(data)
Data_Array_hf = np.array(data_hf).flatten()
hf = Data_Array_hf.tolist()

#长沙 cs
data_cs = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\cs.xlsx")
#print(data)
Data_Array_cs = np.array(data_cs).flatten()
cs = Data_Array_cs.tolist()

#南京 nj
data_nj = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\nj.xlsx")
#print(data)
Data_Array_nj = np.array(data_nj).flatten()
nj = Data_Array_nj.tolist()

#贵阳 gy
data_gy = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\gy.xlsx")
#print(data)
Data_Array_gy = np.array(data_gy).flatten()
gy = Data_Array_gy.tolist()

#昆明 km
data_km = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\km.xlsx")
#print(data)
Data_Array_km = np.array(data_km).flatten()
km = Data_Array_km.tolist()

#南宁 nn
data_nn = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\nn.xlsx")
#print(data)
Data_Array_nn = np.array(data_nn).flatten()
nn = Data_Array_nn.tolist()

#杭州 hz
data_hz = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\hz.xlsx")
#print(data)
Data_Array_hz = np.array(data_hz).flatten()
hz = Data_Array_hz.tolist()

#南昌 nc
data_nc = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\nc.xlsx")
#print(data)
Data_Array_nc = np.array(data_nc).flatten()
nc = Data_Array_nc.tolist()

#福州 fz
data_fz = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\fz.xlsx")
#print(data)
Data_Array_fz = np.array(data_fz).flatten()
fz = Data_Array_fz.tolist()

#海口 hk
data_hk = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\hk.xlsx")
#print(data)
Data_Array_hk = np.array(data_hk).flatten()
hk = Data_Array_hk.tolist()

#武汉 wh
data_wh = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\wh.xlsx")
#print(data)
Data_Array_wh = np.array(data_wh).flatten()
wh = Data_Array_wh.tolist()

#成都 cd
data_cd = pd.read_excel(r"C:\Users\86183\Desktop\python-lxx\city\cd.xlsx")
#print(data)
Data_Array_cd = np.array(data_cd).flatten()
cd = Data_Array_cd.tolist()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 367)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 10, 251, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 10, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 10, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 941, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(30)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 0, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.click_my_btn) #点击按钮，能够返回文本

    def click_my_btn(self):
        str_tmp=self.lineEdit.text()
        #print(str_tmp)
        if str_tmp == 'sh':
            #city = 'sh'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{sh[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'bj':
            city = 'bj'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{bj[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'tj':
            city = 'tj'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{tj[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'cq':
            city = 'cq'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{cq[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)      
        elif str_tmp == 'heb':
            city = 'heb'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{heb[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)   
        elif str_tmp == 'cc':
            city = 'cc'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{cc[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)     
        elif str_tmp == 'sy':
            city = 'sy'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{sy[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)   
        elif str_tmp == 'hhht':
            city = 'hhht'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{hhht[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'sjz':
            city = 'sjz'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{sjz[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)    
        elif str_tmp == 'wlmq':
            city = 'wlmq'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{wlmq[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item) 
        elif str_tmp == 'lz':
            city = 'lz'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{lz[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)   
        elif str_tmp == 'xa':
            city = 'xa'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{xa[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)  
        elif str_tmp == 'yc':
            city = 'yc'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{yc[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)  
        elif str_tmp == 'zz':
            city = 'zz'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{zz[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)  
        elif str_tmp == 'jn':
            city = 'jn'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{jn[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'ty':
            city = 'ty'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{ty[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'hf':
            city = 'hf'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{hf[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'cs':
            city = 'cs'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{cs[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'nj':
            city = 'nj'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{nj[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'gy':
            city = 'gy'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{gy[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'km':
            city = 'km'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{km[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'nn':
            city = 'nn'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{nn[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'hz':
            city = 'hz'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{hz[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'nc':
            city = 'nc'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{nc[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'fz':
            city = 'fz'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{fz[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'hk':
            city = 'hk'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{hk[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'wh':
            city = 'wh'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{wh[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)
        elif str_tmp == 'cd':
            city = 'cd'
            for row in range(30):
                for col in range(9):
                    item = QtWidgets.QTableWidgetItem(f'{cd[row*9+col]}' ) #这里要注意f输出的方法
                    #item = QtWidgets.QTableWidgetItem(a[row*7+col] )
                    self.tableWidget.setItem(row,col,item)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "你要查找的二手房信息的城市名称首字母是："))
        self.pushButton.setText(_translate("MainWindow", "更新数据表格"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "16"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "17"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "18"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "19"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "20"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "21"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "22"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "23"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "24"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "25"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "26"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "27"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "28"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "29"))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "30"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "地址"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "户型"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "面积"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "朝向"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "装修"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "楼层"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "建立"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "结构"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "价格(万元)"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)


        #a=list(range(0,210)) 测试列表
        #将文字一步步输入到表格
        #for i in range(30):
        #    for j in range(8):
        #        self.tableWidget.setItem(0, 0, a[(i+1)*8+j])



        self.tableWidget.setSortingEnabled(__sortingEnabled)
