# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86183\Desktop\python-lxx\project2\untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import pinyin #另外使用pip安装pinyin包

from PyQt5.QtWidgets import QCompleter
from PyQt5 import QtCore, QtGui, QtWidgets

import time


class Ui_Project2_20203578(object):
    def setupUi(self, Project2_20203578):
        Project2_20203578.setObjectName("Project2_20203578")
        Project2_20203578.resize(365, 195)
        self.centralwidget = QtWidgets.QWidget(Project2_20203578)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 191, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 100, 151, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(250, 0, 110, 22))
        self.dateEdit.setDate(QtCore.QDate(2022, 11, 21))
        self.dateEdit.setObjectName("dateEdit")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 140, 361, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        Project2_20203578.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Project2_20203578)
        self.statusbar.setObjectName("statusbar")
        Project2_20203578.setStatusBar(self.statusbar)

        self.retranslateUi(Project2_20203578)
        QtCore.QMetaObject.connectSlotsByName(Project2_20203578)

        #self.combo_box = QtWidgets.QComboBox(self, minimumWidth=150)
        #self.combo_box.setEditable(True)

        self.progressBar.setRange(0, 3)
        time.sleep(1)
        self.progressBar.setValue(1)
        time.sleep(0.8)
        self.progressBar.setValue(2)
        time.sleep(0.5)
        self.progressBar.setValue(3)

        self.auto_complete()

     #模糊匹配
    #items_list=['北京','上海','天津','重庆','哈尔滨','长春','沈阳','呼和浩特','石家庄','乌鲁木齐','兰州','西宁','西安','银川','郑州','济南','太原','合肥','长沙','武汉','南京','成都','贵阳','昆明','南宁','拉萨','杭州','南昌','广州','福州','台北','海口','香港','澳门']
    '''
    completer = QCompleter(items_list)
    completer.setFilterMode(QtCore.Qt.MatchContains) #设置匹配模式为内容匹配
    completer.setCompletionMode(QtWidgets.QCompleter.PopupCompletion) #设置不全模式为全显选项补全
    '''

    def auto_complete(self):
        items_list=['北京','上海','天津','重庆','哈尔滨','长春','沈阳','呼和浩特','石家庄','乌鲁木齐','兰州','西宁','西安','银川','郑州','济南','太原','合肥','长沙','武汉','南京','成都','贵阳','昆明','南宁','拉萨','杭州','南昌','广州','福州','台北','海口','香港','澳门']
        self.completer = QtWidgets.QCompleter(items_list)

        # 设置匹配模式  Qt.MatchContains 内容匹配
        self.completer.setFilterMode(QtCore.Qt.MatchContains)

        # 设置补全模式  QCompleter.PopupCompletion 弹出选项补全（默认）
        self.completer.setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
    
        self.lineEdit.setCompleter(self.completer)
        #self.combo_box.setCompleter(self.completer)

    def click_my_btn(self):
        def getStrAllAplha(str):
            return pinyin.get_initial(str, delimiter="")
        print("你要查看的城市的首字母是：")
        str_tmp=self.lineEdit.text()
        #print(str_tmp)
        self.str=getStrAllAplha(str_tmp)
        print(self.str)  #测试了一下转换字母，好用的

    #def get_str():
    #    return str


    def retranslateUi(self, Project2_20203578):
        _translate = QtCore.QCoreApplication.translate
        Project2_20203578.setWindowTitle(_translate("Project2_20203578", "MainWindow"))
        self.pushButton.setText(_translate("Project2_20203578", "确定"))
        self.label.setText(_translate("Project2_20203578", "欢迎"))
        self.label_2.setText(_translate("Project2_20203578", "请输入您想查看的二手房城市名称："))

        self.label.setStyleSheet("font: bold;color:white")
        self.label_2.setStyleSheet("font: bold;color:white")

        self.lineEdit.setText(_translate("Project2_20203578", "请在这里输入"))
